import Header from './Header/page'
import Footer from './Footer/page'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin:'0'}}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
